## **Introduction**

**Multi-Class Image Classification** Machine Learning project.

We want to determine what **type of class** the image is amongst :

* automobile
* cat
* dog



### 1. Import Libraries

In [2]:
import numpy as np
import pandas as pd

## 2. Import files.

File format and explanation:

* There are **5 train** files (data_batch_1, data_batch_2, ...), **one test** (test_batch) and **label names** (batches.meta).
* The dataset consists of **60,000** 32x32 colour images in 10 classes, with **6,000** images per class.
* There are **50,000 training images** and **10,000 test images.**
* Each file contains a dictionary with the following elements:

    * **data:** a 10,000 x 3,072 numpy array of uint8s. Each row of the array stores a 32 x 32 colour image. The first 1,024 entries contain the red channel values, the next 1,024 the green, and the final 1,024 the blue. The image is stored in row-major order, so that the first 32 entries of the array are the red channel values of the first row of the image.
    <br>
    <br>
    * **labels**: a list of 10,000 numbers in the range 0-9. The number at index i indicates the label of the ith image in the array **data.**


Images available from :

* airplane
* automobile
* bird
* cat
* deer
* dog
* frog
* horse
* ship
* truck



In [53]:
# Get the labels, transform type from byte to string and store them in label array.

def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
        labels = dict[b'label_names']
    return labels

file = "./data/batches.meta"

byte_labels = unpickle(file)

# Show labels
print(byte_labels)

# b'This is a byte object.' => We need to convert it to string
print(type(byte_labels[0]))

labels =  list(map(lambda x: x.decode('utf-8'),byte_labels))
print(type(labels[0]))
print(labels)


[b'airplane', b'automobile', b'bird', b'cat', b'deer', b'dog', b'frog', b'horse', b'ship', b'truck']
<class 'bytes'>
<class 'str'>
['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [83]:
# Function to unwrap 
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')

    # Each batch contains 10,000 images
    print(len(dict[b'labels']),"images each represented with a number ranging from 0 to 9")

    print((dict.keys()))


    print((dict[b'data']))
    # 32 x 32 = 1024
    print(len((dict[b'data'][0])))



file = "./data/data_batch_1"

unpickle(file)


10000 images each represented with a number ranging from 0 to 9
dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 71  60  74 ...  68  69  68]
 [250 254 211 ... 215 255 254]
 [ 62  61  60 ... 130 130 131]]
3072
